/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-ori_omer
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_ORI_OMER_API_H
#define INCLUDED_ORI_OMER_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_ori_omer_EXPORTS
#define ORI_OMER_API __GR_ATTR_EXPORT
#else
#define ORI_OMER_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_ORI_OMER_API_H */
